on_internal_error: refactor log_error_and_backtrace
Extract the common code to print the internal error
followed by a backtrace into a common function.

Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit f7e5d1e925cca29f291479cdca8eed1c8e3660d1)